[package]
name = "gelatyx"
description = "Format codebease inside the docs"
version = "0.1.4"
edition = "2021"
authors = ["azzamsa <vcs@azzamsa.com>"]
repository = "https://github.com/azzamsa/gelatyx"
keywords = ["cli", "formatter"]
categories = ["command-line-utilities"]
license = "MIT"
exclude = ["/README.md"]

[profile.release]
opt-level = 'z'  # Optimize for size.
codegen-units = 1
lto = true
panic = 'abort'

[features]
default = ["lua"]
lua = ["dep:stylua"]

[dependencies]
# cli
clap = { version = "3.2.12", features = ["suggestions", "cargo"] }
ansi_term = "0.12.1"
wild = "2.0.4"
atty = "0.2.14"

# error
thiserror = "1.0.31"

# formatter
stylua = { version = "0.14.0", optional = true }

regex = "1.6.0"
toml = "0.5.9"


[dev-dependencies]
# test
assert_cmd = "2.0.4"
predicates = "2.1.1"
anyhow = "1.0.58"

cargo-husky = { version = "1", features = ["user-hooks"] }
