[package]
name = "gelatyx"
description = "Format codebease inside the docs"
version = "0.1.1"
edition = "2021"
authors = ["azzamsa <vcs@azzamsa.com>"]
repository = "https://github.com/azzamsa/gelatyx"
keywords = ["cli", "formatter"]
categories = ["command-line-utilities"]
license = "MIT"
exclude = ["/README.md"]

[profile.release]
opt-level = 'z'  # Optimize for size.
codegen-units = 1
lto = true
panic = 'abort'

[features]
default = ["lua"]
lua = ["dep:stylua"]

[dependencies]
clap = { version = "3.2.10", features = ["suggestions", "cargo"] }

anyhow = "1.0.58"
thiserror = "1.0.31"

regex = "1.6.0"
glob = "0.3.0"

stylua = { version = "0.14.0", optional = true }

[dev-dependencies]
rusty-hook = "^0.11.2"
assert_cmd = "2.0.4"
predicates = "2.1.1"
