[package]
name = "gelatyx"
version = "0.1.5"
authors = ["azzamsa <vcs@azzamsa.com>"]
categories = ["command-line-utilities"]
edition = "2021"
exclude = ["/README.md"]
keywords = ["cli", "formatter"]
license = "MIT"
repository = "https://github.com/azzamsa/gelatyx"
description = "Format codebease inside the docs"

[profile.release]
opt-level = 'z' # Optimize for size.
codegen-units = 1
lto = true
panic = 'abort'

[features]
default = ["lua"]
lua = ["dep:stylua"]

[dependencies]
# cli
ansi_term = "0.12.1"
atty = "0.2.14"
wild = "2.0"

# error
anyhow = "1.0"
thiserror = "1.0"

# formatter
stylua = { version = "0.14.0", optional = true }

full_moon = "0.15.1"
regex = "1.6"
toml = "0.5.9"

[dependencies.clap]
version = "4.0.30"
features = ["suggestions", "color", "cargo", "derive"]

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"

cargo-husky = { version = "1", features = ["user-hooks"] }
